# Generated by Django 4.2.3 on 2024-02-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file',
        ),
        migrations.AddField(
            model_name='resume',
            name='my_file',
            field=models.FileField(blank=True, upload_to='doc'),
        ),
    ]
